### ISSUE TITLE
Can't install app without providing Spotify username.

### ISSUE THREAD

**Issue by elvirolo** [YunoHost-Apps/mopidy_ynh#2]
Mopidy cannot be installed without providing a Spotify username. This should not be compulsory.

**Comment by frju365** [comment]
Hello, 
Thanks for reporting it,
That will surely be solved in my PR : https://github.com/YunoHost-Apps/mopidy_ynh/pull/3
frju365

**Comment by elvirolo** [comment]
Hi! Your PR didn't work. I made another one which does  #4 . Thanks for showing me where to look at :)

**Comment by frju365** [comment]
In fact, my PR works fine. :~

**Comment by frju365** [comment]
Of course my PR was not committed yes. It's a PR. I'm not the maintainer of the package, so I need @magikcypress to approve my PR before merging it.

**Comment by elvirolo** [comment]
You're right, my mistake. Sorry about that.

**Comment by frju365** [comment]
No problem :)
