### ISSUE TITLE
No sound

### ISSUE THREAD

**Issue by TROMsite** [YunoHost-Apps/mopidy_ynh#21]
I am testing it at https://music.trom.tf/ but although it can seem to play everything, I get no sound output. Tried in Firefox and Chromium.

### Context

- Hardware: *VPS bought online
- YunoHost version:  4.1.8 (stable).
- I have access to my server: *Through SSH | through the webadmin | direct access via keyboard / screen | ...*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no
- Using, or trying to install package version/branch: 3.1.1

**Comment by siwinter** [comment]
Thanks for testing the app.
Mopidy tries to play the sounds on the audio hardware of your server.
This means that you need a real server with its own audio hardware to be able to use the app. 
The user interface in the browser only serves as a kind of remote control.

I will try to describe this more clearly in the docs.

**Comment by TROMsite** [comment]
Ah ok makes sense. Yes please specify that in the readme. Many people, like me, are using a cloud vps for ynh. Cheers!
