### ISSUE TITLE
blank installation page

### ISSUE THREAD

**Issue by eetsceeck1** [YunoHost-Apps/mopidy_ynh#32]
Hi,
empty page on yunohost?
any idea?
thanks
![rgt16koGQT](https://user-images.githubusercontent.com/43915916/132863323-50564750-5fc8-444d-ac14-29ad4c2fd0e0.png)

**Comment by siwinter** [comment]
should work now

**Comment by eetsceeck1** [comment]
Works now, thank you very much!
