### ISSUE TITLE
Error 502 when accessing app

### ISSUE THREAD

**Issue by elvirolo** [YunoHost-Apps/mopidy_ynh#7]
Mopidy now installs fine (see install log [there](https://paste.debian.net/982686/)), but I get an Error 502 Bad Gateway when I open it from the user interface.

**Comment by stilobique** [comment]
I'm look your log, but is it not accesible ; can you paste it inside Github ? It's your Mopidy Log ? Can you share your Nginx log ?

I'm like you, my service is install but don't work, i search if it's a Mopidy error or something else.

**Comment by siwinter** [comment]
The app has been completely redesigned.
If this does not solve the problem, please open a new issue.
